### ISSUE TITLE
» ғᴀɪʟᴇᴅ ᴛᴏ ᴘʀᴏᴄᴇss ǫᴜᴇʀʏ.

### ISSUE THREAD

**Issue by ItzMeRadha** [Pranav-Saraswat/Testing-Alpha1#15]
When I try to play a song with a youtube link it shows that I failed to process the query.

**Comment by Pranav-Saraswat** [comment]
some links may not working try another links also to test it

**Comment by Pranav-Saraswat** [comment]
I tried with youtube link its working well try to change your ip address may be issue in your ip

**Comment by ItzMeRadha** [comment]
> some links may not working try another links also to test it

Yep

**Comment by ItzMeRadha** [comment]
> I tried with youtube link its working well try to change your ip address may be issue in your ip

Na bro

**Comment by ITZ-ZAID** [comment]
@ItzMeRadha Soja bhai

**Comment by ItzMeRadha** [comment]
> @ItzMeRadha Soja bhai

Okay boo bhai

**Comment by Pranav-Saraswat** [comment]
well I checked I'm not face any error just try to change your machine
